# Generated by Django 3.2.9 on 2021-11-13 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evreka2', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bin',
            name='operation_id',
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection_time', models.DateTimeField()),
                ('bin_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evreka2.bin')),
                ('operation_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evreka2.operation')),
            ],
        ),
    ]
